### ISSUE TITLE
Goal/Level

### ISSUE THREAD

**Issue by rstahl25** [rstahl25/SWE_Walsh#4]
Have an end goal to reach at the end of each level

Done:

1.At the end of each level, the character reaches a goal
2.Each level has a unique goal
3.The goal in each level will be an academic building on campus (i.e. GLC, Timken, Barrett, etc.)

**Comment by mcaldwel1** [comment]
Given: The user is looking at a level...  
When: The level starts... 
Then: The Goal/Level design displays at the far right side of the canvas 

Given: The player reaches the goal
When: The player reaches the x,y coordinates of the goal/design placement
Then: The level concludes and the menu screen is displayed
