### ISSUE TITLE
Horizontal Movement

### ISSUE THREAD

**Issue by ryan-moorhead** [rstahl25/SWE_Walsh#6]
The sprite can move horizontally both to the left and right.

Done: when the left arrow key is pressed, then the player moves to the left. When the right arrow key is pressed, then the player moves to the right.

**Comment by JeremyHam** [comment]
Given that a character representation appears on the screen, when the user pushes the left arrow key, then the player will move to the left.

**Comment by JeremyHam** [comment]
Given that a player representation appears on the screen, when the right arrow key is pressed, the player will move to the right.

**Comment by JeremyHam** [comment]
Given that a player will representation appears on screen, when the up arrow key is pressed, then the player will jump.
